/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    println ("¡Hola Kotlin!")
    
    val nombre = "Iván"
    val apellido = "Roth"
    val fecha = "22/04"

    println("Mi nombre es $nombre $apellido")
    println("Hoy es $fecha")
}


